[phases.setup]
nixPkgs = ['python310']
aptPkgs = ['...', 'ffmpeg', 'espeak', 'libavcodec-extra']
[phases.install]
cmds = ['python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt && pip install -r requirements-optional.txt']
[start]
cmd = "python ./app.py"